// Copyright (c) Strange Loop Games. All rights reserved.
// See LICENSE file in the project root for full license information.
// <auto-generated from BlockTemplate.tt/>

namespace Eco.Mods.TechTree
{
    using System;
    using System.Collections.Generic;
    using Eco.Gameplay.Components;
    using Eco.Gameplay.Items;
    using Eco.Gameplay.Skills;
    using Eco.Core.Items;
    using Eco.Shared.Localization;
    using Eco.Shared.Serialization;
    using Eco.Shared.SharedTypes;
    using Eco.World.Blocks;
    using Eco.Gameplay.Items.Recipes;
    using System.ComponentModel;

    [Serialized]
    [Solid, Wall, Diggable]
    [RequiresSkill(typeof(MiningSkill), 1)]
    [Tag(BlockTags.Diggable)]
        public partial class CrushedIronOreBlock :
        Block
        , IRepresentsItem
    {
        public virtual Type RepresentedItemType { get { return typeof(CrushedIronOreItem); } }
    }

    [Serialized]
    [LocDisplayName("Crushed Iron Ore")]
    [LocDescription("Crushed iron ore that is ready to be concentrated.")]
    [MaxStackSize(10)]
    [Weight(30000)]
    [StartsDiscovered]
    [Ecopedia("Blocks", "Processed Rock", createAsSubPage: true)]
    [Category("Hidden")]
    [Tag("Excavatable")]
    [RequiresTool(typeof(ShovelItem))]
    public partial class CrushedIronOreItem :
 
    BlockItem<CrushedIronOreBlock>
    {
        public override LocString DisplayNamePlural { get { return Localizer.DoStr("Crushed Iron Ore"); } }

        public override bool CanStickToWalls { get { return false; } }
    }

}
